

INSERT INTO users VALUES (1, 'admin', '$2a$10$LUWQRdDcibuBebYuxPMcv.xeMwdRGgTyBY92V4HB9C4B92qbNpTEu');

INSERT INTO roles VALUES (1,'ROLE_ADMIN');
INSERT INTO roles VALUES (2,'ROLE_USER');
INSERT INTO user_roles VALUES (1, 1);